name: build
on:
  release:
    types: [created]
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - run: npm install -g npm@11 --registry=https://registry.npmjs.org
      - uses: microbit-foundation/npm-package-versioner-action@v3
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run ci
      - name: Upload GitHub packages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: ./storybook-static
      - run: npm publish --allow-directory=all
        if: github.event_name == 'release' && github.event.action == 'created'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
